/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import java.time.LocalDate

fun main() {
    nombreyapellido()
    tiposdefuncion()
    rectangulo()
    println(paroimpar(4))
    println(paroimpar(9))
    println(numpositoneg(8))
    println(numpositoneg(-3))
}

fun nombreyapellido () {
    val nombre = "Paloma"
    val apellido = "Junent"
    val fecha = LocalDate.now()
    println("¡Hola, Kotlin!")
    println(" Tu nombre completo es $nombre $apellido")
    println("Hoy es $fecha")
}

fun tiposdefuncion () {
    val nombre: String = "Paloma"
    val edad: Int = 16
    val altura: Double = 1.54
    val esEstudiante: Boolean = true

    println("nombre : $nombre")
    println("edad : $edad")
    println("altura : $altura")
    println("es estudiante? : $esEstudiante")
}

fun rectangulo () {
    val alt: Double = 4.5
    val base: Double = 2.25
    val area = base * alt

    println(" El área del rectángulo es : $area")

}


fun paroimpar (numero: Int): String { 
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }       
}

fun numpositoneg (numero: Int): String {
    return when {
        numero < 0 -> "negativo"
        numero > 0 -> "positivo"
        else -> "cero"
    }
}